# Generated by Django 3.1.7 on 2021-03-28 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_process', '0001_initial'),
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abbreviationdirectories',
            options={'verbose_name': 'Отношение аббревиатуры и дирекции', 'verbose_name_plural': 'Отношения аббревиатур и дирекций'},
        ),
        migrations.AddField(
            model_name='abbreviationrules',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review_process.project', verbose_name='Проект, к которому относятся правила'),
        ),
        migrations.AddField(
            model_name='appstructurerules',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review_process.project', verbose_name='Проект, к которому относятся правила'),
        ),
        migrations.AddField(
            model_name='docstringmethodsrules',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review_process.project', verbose_name='Проект, к которому относятся правила'),
        ),
        migrations.AddField(
            model_name='projectstructurerules',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review_process.project', verbose_name='Проект, к которому относятся правила'),
        ),
        migrations.AlterField(
            model_name='djangoapps',
            name='app_name_ru',
            field=models.CharField(max_length=128, verbose_name='Название модуля'),
        ),
        migrations.AlterField(
            model_name='djangoapps',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание модуля'),
        ),
    ]
