# Generated by Django 3.1.7 on 2021-04-18 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_process', '0001_initial'),
        ('knowledge_base', '0002_auto_20210328_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appstructuredirectories',
            options={'verbose_name': 'Директория, к которой относится правило', 'verbose_name_plural': 'Директории, к которым относятся правила'},
        ),
        migrations.AlterModelOptions(
            name='appstructureprojectfiles',
            options={'verbose_name': 'Файл, который должен быть в модуле', 'verbose_name_plural': 'Файлы, которые должны быть в модуле'},
        ),
        migrations.AddField(
            model_name='docstringparams',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review_process.project', verbose_name='Проект, к которому относятся правила'),
        ),
    ]
