# Generated by Django 3.1.7 on 2022-06-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_process', '0001_initial'),
        ('knowledge_base', '0003_auto_20210418_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=123, verbose_name='Название метода в API')),
            ],
            options={
                'verbose_name': 'Правило на структуру API',
                'verbose_name_plural': 'Правила на структуру API',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=123, verbose_name='Тип связи')),
            ],
            options={
                'verbose_name': 'Тип связи',
                'verbose_name_plural': 'Типы связи',
            },
        ),
        migrations.CreateModel(
            name='Notion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion_text', models.CharField(max_length=200, verbose_name='Понятие')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание понятия')),
            ],
            options={
                'verbose_name': 'Понятие',
                'verbose_name_plural': 'Понятия',
            },
        ),
        migrations.AlterModelOptions(
            name='abbreviationdirectories',
            options={'verbose_name': 'Дирекция, к которой относится аббревиатура', 'verbose_name_plural': 'Дирекции, к которым относится аббревиатура'},
        ),
        migrations.AddField(
            model_name='abbreviationrules',
            name='abbreviation_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Присутсвует'), (2, 'Не присутствует')], null=True, verbose_name='Тип аббревиатуры'),
        ),
        migrations.CreateModel(
            name='NotionToNotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge_base.link', verbose_name='Тип связи')),
                ('next_notion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base_notiontonotion_next_notions', to='knowledge_base.notion', verbose_name='Следующее понятие')),
                ('prev_notion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base_notiontonotion_prev_notions', to='knowledge_base.notion', verbose_name='Предыдущее понятие')),
            ],
            options={
                'verbose_name': 'Следующее понятие',
                'verbose_name_plural': 'Следующие понятия',
            },
        ),
        migrations.AddField(
            model_name='notion',
            name='next_notion',
            field=models.ManyToManyField(related_name='knowledge_base_notion_notions', through='knowledge_base.NotionToNotion', to='knowledge_base.Notion', verbose_name='Следующее понятие'),
        ),
        migrations.CreateModel(
            name='APIStructureProjectFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_base.apirules')),
                ('project_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_base.projectfile', verbose_name='Файл в проекте')),
            ],
            options={
                'verbose_name': 'Файл, к которому относится правило',
                'verbose_name_plural': 'Файлы, к которым относится правило',
            },
        ),
        migrations.CreateModel(
            name='APIStructureDirectories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_base.apirules')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_base.djangoapps', verbose_name='Директория')),
            ],
            options={
                'verbose_name': 'Директория, к которой относится правило',
                'verbose_name_plural': 'Директории, к которым относятся правила',
            },
        ),
        migrations.AddField(
            model_name='apirules',
            name='directory',
            field=models.ManyToManyField(blank=True, related_name='knowledge_base_apirules_directories', through='knowledge_base.APIStructureDirectories', to='knowledge_base.DjangoApps', verbose_name='Директории к которым относится правило'),
        ),
        migrations.AddField(
            model_name='apirules',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review_process.project', verbose_name='Проект, к которому относятся правила'),
        ),
        migrations.AddField(
            model_name='apirules',
            name='project_files',
            field=models.ManyToManyField(blank=True, through='knowledge_base.APIStructureProjectFiles', to='knowledge_base.ProjectFile', verbose_name='Файлы, к которым относится правило'),
        ),
    ]
